name: Code quality and formatting

on:
  push:
    paths:
      - '.github/workflows/backend.yml'
      - 'src/**'
      - 'Cargo.toml'
  pull_request:
    paths:
      - '.github/workflows/backend.yml'
      - 'src/**'
      - 'Cargo.toml'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  rustfmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path ./Cargo.toml --all -- --check

  clippy:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path ./Cargo.toml --all -- -D warnings